# -*- coding: utf-8 -*-
"""dashboard3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1po_TOTGicplGqxSvB-CYjDL4fZnqqBGx
"""

import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="E-Commerce Public Dataset",
    page_icon="🛒",
    layout="wide"
)

st.title("🛒 E-Commerce Public Dataset Dashboard")
st.caption("Dashboard sederhana untuk analisis transaksi e-commerce di São Paulo")

#LOAD DATA

@st.cache_data
def load_data():
    orders = pd.read_csv("/content/alldata/orders_dataset.csv")
    order_items = pd.read_csv("/content/alldata/order_items_dataset.csv")
    customers = pd.read_csv("/content/alldata/customers_dataset.csv")
    products = pd.read_csv("/content/alldata/products_dataset.csv")
    category_translation = pd.read_csv("/content/alldata/product_category_name_translation.csv")
    sellers = pd.read_csv("/content/alldata/sellers_dataset.csv")

@st.cache_data
def load_data():
    orders = pd.read_csv("/content/alldata/orders_dataset.csv")
    order_items = pd.read_csv("/content/alldata/order_items_dataset.csv")
    customers = pd.read_csv("/content/alldata/customers_dataset.csv")
    products = pd.read_csv("/content/alldata/products_dataset.csv")
    category_translation = pd.read_csv("/content/alldata/product_category_name_translation.csv")
    sellers = pd.read_csv("/content/alldata/sellers_dataset.csv")

    # Konversi datetime
    date_cols = [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
    for c in date_cols:
        orders[c] = pd.to_datetime(orders[c], errors="coerce")

    order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"], errors="coerce")

    # Data cleaning
    orders_clean = orders[orders["order_status"] == "delivered"].copy()
    products["product_category_name"] = products["product_category_name"].fillna("unknown")
    products = products.merge(category_translation, on="product_category_name", how="left")
    products["product_category_name_english"] = products["product_category_name_english"].fillna("unknown")

    # Merge utama
    df = (
        orders_clean
        .merge(order_items, on="order_id", how="left")
        .merge(customers, on="customer_id", how="left")
        .merge(products[["product_id", "product_category_name_english"]], on="product_id", how="left")
        .merge(sellers[["seller_id", "seller_city", "seller_state"]], on="seller_id", how="left")
    )

    # Feature engineering
    df["order_year"] = df["order_purchase_timestamp"].dt.year
    df["order_month"] = df["order_purchase_timestamp"].dt.month
    df["delivery_delay"] = (
        df["order_delivered_customer_date"] - df["order_estimated_delivery_date"]
    ).dt.days
    df["is_on_time"] = df["delivery_delay"] <= 0
    df["delivery_days"] = (
        df["order_delivered_customer_date"] - df["order_purchase_timestamp"]
    ).dt.days

    return df

df = load_data()

# SIDEBAR FILTER
# =========================
st.sidebar.header("Filter")
years = sorted(df["order_year"].dropna().unique())
selected_years = st.sidebar.multiselect("Pilih Tahun", years, default=years)

states = sorted(df["customer_state"].dropna().unique())
selected_state = st.sidebar.selectbox("Pilih State Pelanggan", ["SP"] + [s for s in states if s != "SP"])

df_filtered = df[
    (df["order_year"].isin(selected_years)) &
    (df["customer_state"] == selected_state)
].copy()

# KPI
# =========================
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Total Orders", f"{df_filtered['order_id'].nunique():,}")

with col2:
    st.metric("Total Revenue", f"BRL {df_filtered['price'].sum():,.2f}")

with col3:
    st.metric("On-Time Rate", f"{df_filtered['is_on_time'].mean()*100:.2f}%")

with col4:
    st.metric("Avg Freight Value", f"BRL {df_filtered['freight_value'].mean():,.2f}")

st.divider()

# VISUALISASI
# =========================
colA, colB = st.columns(2)

with colA:
    st.subheader("Top 10 Kategori Produk")
    top_cat = df_filtered["product_category_name_english"].value_counts().head(10)

    fig, ax = plt.subplots(figsize=(8, 4))
    sns.barplot(x=top_cat.values, y=top_cat.index, ax=ax)
    ax.set_xlabel("Jumlah Order")
    ax.set_ylabel("Kategori")
    st.pyplot(fig)

with colB:
    st.subheader("Revenue per Kategori")
    revenue_cat = (
        df_filtered.groupby("product_category_name_english")["price"]
        .sum()
        .sort_values(ascending=False)
        .head(10)
    )

    fig, ax = plt.subplots(figsize=(8, 4))
    sns.barplot(x=revenue_cat.values, y=revenue_cat.index, ax=ax)
    ax.set_xlabel("Total Revenue (BRL)")
    ax.set_ylabel("Kategori")
    st.pyplot(fig)

colC, colD = st.columns(2)

with colC:
    st.subheader("Distribusi Delivery Delay")
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.hist(df_filtered["delivery_delay"].dropna(), bins=30)
    ax.set_xlabel("Delay (hari)")
    ax.set_ylabel("Frekuensi")
    st.pyplot(fig)

with colD:
    st.subheader("Correlation Matrix")
    corr_cols = ["price", "freight_value", "delivery_days", "delivery_delay"]
    corr = df_filtered[corr_cols].corr()

    fig, ax = plt.subplots(figsize=(8, 4))
    sns.heatmap(corr, annot=True, cmap="coolwarm", center=0, ax=ax)
    st.pyplot(fig)

st.divider()

# INSIGHT SINGKAT
# =========================
st.subheader("Insight Sederhana")

top_category = top_cat.index[0] if len(top_cat) > 0 else "-"
top_category_count = int(top_cat.iloc[0]) if len(top_cat) > 0 else 0

insight1, insight2, insight3 = st.columns(3)

with insight1:
    st.info(f"Kategori paling banyak dibeli: **{top_category}** ({top_category_count:,} order)")

with insight2:
    st.info(f"On-time delivery rate: **{df_filtered['is_on_time'].mean()*100:.2f}%**")

with insight3:
    st.info(f"Rata-rata delivery days: **{df_filtered['delivery_days'].mean():.1f} hari**")

st.divider()

# TABEL DATA
# =========================
st.subheader("Data Sample")
show_cols = [
    "order_id",
    "order_purchase_timestamp",
    "customer_state",
    "product_category_name_english",
    "price",
    "freight_value",
    "delivery_delay",
    "is_on_time"
]
st.dataframe(df_filtered[show_cols].head(20), use_container_width=True)
