# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LybC_6XNfO0r7p-wqilZuFcrIxBIH7d
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from babel.numbers import format_currency
sns.set(style='dark')

all_df = pd.read_csv("/content/all_data.csv")

datetime_columns = ["order_purchase_timestamp"]
all_df.sort_values(by="order_purchase_timestamp", inplace=True)
all_df.reset_index(inplace=True)

for column in datetime_columns:
    all_df[column] = pd.to_datetime(all_df[column])

min_date = all_df["order_purchase_timestamp"].min()
max_date = all_df["order_purchase_timestamp"].max()

with st.sidebar:
    # Menambahkan logo perusahaan
    st.image("https://github.com/dicodingacademy/assets/raw/main/logo.png")

    # Mengambil start_date & end_date dari date_input
    start_date, end_date = st.date_input(
        label='Rentang Waktu',min_value=min_date,
        max_value=max_date,
        value=[min_date, max_date]
    )

main_df = all_df[(all_df["order_purchase_timestamp"] >= str(start_date)) &
                (all_df["order_purchase_timestamp"] <= str(end_date))]

st.header('Dicoding Collection Dashboard :sparkles:')

def get_top_categories_by_orders(df):
    top_categories_orders = df.groupby('product_category_name_english')['order_id'].nunique().sort_values(ascending=False).head(10).reset_index()
    top_categories_orders.rename(columns={'order_id': 'order_count'}, inplace=True)
    return top_categories_orders

def get_top_categories_by_revenue(df):
    top_categories_revenue = df.groupby('product_category_name_english')['price'].sum().sort_values(ascending=False).head(10).reset_index()
    top_categories_revenue.rename(columns={'price': 'total_revenue'}, inplace=True)
    return top_categories_revenue

def get_avg_price_vs_freight(df):
    avg_price_freight_data = df.groupby('product_category_name_english').agg(
        avg_price=('price', 'mean'),
        avg_freight=('freight_value', 'mean'),
        jumlah_order=('order_id', 'count')
    ).sort_values('jumlah_order', ascending=False).head(10)
    return avg_price_freight_data

# Prepare data for plots
top_categories_orders_df = get_top_categories_by_orders(main_df)
top_categories_revenue_df = get_top_categories_by_revenue(main_df)
avg_price_freight_df = get_avg_price_vs_freight(main_df)

"""## Customer Demographics"""

col1, col2, col3 = st.columns(3)

with col1:
    total_orders = main_df['order_id'].nunique()
    st.metric('Total Orders', value=total_orders)

with col2:
    total_revenue = format_currency(main_df['price'].sum(), 'BRL', locale='es_CO')
    st.metric('Total Revenue', value=total_revenue)

"""## Product Analysis"""

st.subheader("Performing Product By Ordered Items vs Revenue")

# Plot 1: Top 10 kategori berdasarkan jumlah order
fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(x='order_count', y='product_category_name_english', data=top_categories_orders_df, palette='viridis', ax=ax)
ax.set_title('Top 10 Product Categories by Order Count')
ax.set_xlabel('Order Count')
ax.set_ylabel('Product Category')
st.pyplot(fig)

# Plot 2: Top 10 kategori berdasarkan total revenue
fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(x='total_revenue', y='product_category_name_english', data=top_categories_revenue_df, palette='magma', ax=ax)
ax.set_title('Top 10 Product Categories by Total Revenue')
ax.set_xlabel('Total Revenue (BRL)')
ax.set_ylabel('Product Category')
st.pyplot(fig)

"""## Kategori produk apa saja yang memberikan kontribusi terbesar terhadap total penjualan seller berdasarkan jumlah unit terjual dan omzet selama 2017

## Price vs Freight Analysis
"""

st.subheader("Average Price vs Average Freight Value")
# Plot 4: Average Price vs Average Freight Value
fig, ax = plt.subplots(figsize=(12, 7))
scatter_data = avg_price_freight_df

ax.scatter(
    scatter_data['avg_price'],
    scatter_data['avg_freight'],
    s=scatter_data['jumlah_order'] / 2,
    alpha=0.6,
    c=range(len(scatter_data)),
    cmap='viridis'
)

for kategori, row in scatter_data.iterrows():
    ax.annotate(
        kategori,
        (row['avg_price'], row['avg_freight']),
        xytext=(7, 5),
        textcoords='offset points',
        fontsize=9
    )

ax.set_title('Average Price vs Freight Value', fontsize=14, fontweight='bold')
ax.set_xlabel('Average Price (BRL)')
ax.set_ylabel('Average Freight Value (BRL)')
ax.grid(alpha=0.2)
plt.tight_layout()
st.pyplot(fig)

def get_category_sales_contribution(df):
    category_sales_df = df.groupby('product_category_name_english').agg(
        total_units_sold=('product_id', 'count'),
        total_revenue=('price', 'sum')
    ).reset_index()
    category_sales_df = category_sales_df.sort_values(by='total_revenue', ascending=False).head(15)
    return category_sales_df

category_sales_contribution_df = get_category_sales_contribution(main_df)

"""## Product Category Sales Contribution (Top 15)"""

fig, ax = plt.subplots(figsize=(12, 8))

# Scatter plot for units sold vs total revenue
sns.scatterplot(
    x='total_units_sold',
    y='total_revenue',
    hue='product_category_name_english',
    size='total_revenue', # Size dots by total revenue
    sizes=(100, 1000), # Range of marker sizes
    data=category_sales_contribution_df,
    palette='viridis',
    legend='brief',
    ax=ax
)

# Add category names as annotations
for i, row in category_sales_contribution_df.iterrows():
    ax.annotate(
        row['product_category_name_english'],
        (row['total_units_sold'], row['total_revenue']),
        xytext=(5, 5),
        textcoords='offset points',
        fontsize=9,
        ha='left',
        va='bottom'
    )

ax.set_title('Top 15 Product Categories: Units Sold vs. Total Revenue', fontsize=14, fontweight='bold')
ax.set_xlabel('Total Units Sold')
ax.set_ylabel('Total Revenue (BRL)')
ax.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
st.pyplot(fig)

